runtime: php72
service: line-bot-php

env_variables:
  ENV: __ENV__
  APP_NAME: Laravel
  APP_DEBUG: true
  APP_KEY: __APP_KEY__
  APP_STORAGE: /tmp
  APP_TIMEZONE: Asia/tokyo
  VIEW_COMPILED_PATH: /tmp
  LOG_CHANNEL: syslog
  SESSION_DRIVER: cookie
  DB_HOST: 127.0.0.1
  DB_DATABASE: __DB_DATABASE__
  DB_USERNAME: __DB_USERNAME__
  DB_PASSWORD: __DB_PASSWORD__
  DB_DSN: __DB_DSN__
