steps:
- id: 'build'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'PHP_VERSION=${_TAG}', '--no-cache', '-f', 'docker/Dockerfile.composer', '-t', 'gcr.io/$PROJECT_ID/composer:$_TAG', '.']
- id: 'composer install'
  name: 'gcr.io/$PROJECT_ID/composer:$_TAG'
  args: ["install"]
- id: "LINE Messaging API ACCESS_TOKEN 置換"
  name: 'ubuntu'
  entrypoint: 'bash'
  args: ['-c', 'sed -i -e s#__ACCESS_TOKEN__#$_ACCESS_TOKEN# app.yaml']
- id: "LINE Messaging API SECRET_TOKEN 置換"
  name: 'ubuntu'
  entrypoint: 'bash'
  args: ['-c', 'sed -i -e s#__SECRET_TOKEN__#$_SECRET_TOKEN# app.yaml']
- id: 'AppEngineへデプロイ'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'app', 'deploy', 'app.yaml', "--no-cache"]
images:
  - 'gcr.io/$PROJECT_ID/composer:$_TAG'
substitutions:
  _TAG: '7.2'
